print("##############################")
print("#                            #")
print("#   Noufal Raditya Wardana   #")
print("#       2510817220019        #")
print("#                            #")
print("##############################")